use chrono::Utc;
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    os::unix::fs::PermissionsExt,
    path::PathBuf,
    process::{Command, Output},
};

mod cases;

const BUN_OUTPUT: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.npmjs.org/left-pad/-/left-pad-1.3.0.tgz"
"#;

const DOTNET_OUTPUT: &str = r#"{
  "version": 1,
  "parameters": "--include-transitive",
  "projects": [{
    "path": "Project.csproj",
    "frameworks": [{
      "framework": "net10.0",
      "topLevelPackages": [{
        "id": "Humanizer.Core",
        "requestedVersion": "2.14.1",
        "resolvedVersion": "2.14.1"
      }],
      "transitivePackages": [{
        "id": "Microsoft.Extensions.Options",
        "resolvedVersion": "10.0.2"
      }]
    }]
  }]
}"#;

const EMPTY_DOTNET_OUTPUT: &str = r#"{
  "version": 1,
  "parameters": "--include-transitive",
  "projects": [{
    "path": "Project.csproj",
    "frameworks": [{"framework": "net10.0"}]
  }]
}"#;

#[derive(Clone, Copy)]
enum FakeBehavior {
    Valid(&'static str),
    Malformed,
    Oversized,
    Failing,
    Hanging,
}

struct Fixture {
    directory: tempfile::TempDir,
    project: PathBuf,
    bin: PathBuf,
    cache: PathBuf,
}

impl Fixture {
    fn new() -> Self {
        let directory = tempfile::tempdir().expect("create test directory");
        let project = directory.path().join("project");
        let bin = directory.path().join("bin");
        let cache = directory.path().join("cache");
        fs::create_dir(&project).expect("create project directory");
        fs::create_dir(&bin).expect("create fake executable directory");
        fs::create_dir(&cache).expect("create cache directory");
        Self {
            directory,
            project,
            bin,
            cache,
        }
    }

    fn bun_project(&self) {
        fs::write(self.project.join("bun.lockb"), b"binary fixture")
            .expect("write binary lock placeholder");
        fs::write(
            self.project.join("package.json"),
            r#"{"dependencies":{"left-pad":"^1.3.0"}}"#,
        )
        .expect("write package manifest");
    }

    fn bun_workspace_project(&self) {
        fs::write(self.project.join("bun.lockb"), b"binary fixture")
            .expect("write binary lock placeholder");
        fs::write(
            self.project.join("package.json"),
            r#"{
                "workspaces":["packages/*"],
                "dependencies":{"root-production":"^1"},
                "devDependencies":{"root-development":"^2"}
            }"#,
        )
        .expect("write root package manifest");
        let workspace = self.project.join("packages/member");
        fs::create_dir_all(&workspace).expect("create workspace package");
        fs::write(
            workspace.join("package.json"),
            r#"{
                "dependencies":{"workspace-production":"^3"},
                "devDependencies":{"workspace-development":"^4"}
            }"#,
        )
        .expect("write workspace package manifest");
    }

    fn bun_lock_only(&self) {
        fs::write(self.project.join("bun.lockb"), b"binary fixture")
            .expect("write binary lock placeholder");
    }

    fn dotnet_project(&self) {
        fs::write(
            self.project.join("Project.csproj"),
            r#"<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="Humanizer.Core" Version="2.14.1" /></ItemGroup></Project>"#,
        )
        .expect("write .NET project");
    }

    fn install(&self, tool: &str, behavior: FakeBehavior) {
        let executable = self.bin.join(tool);
        let mut script = String::from(
            "#!/bin/sh\n\
             {\n\
               printf 'argc=<%s>\\n' \"$#\"\n\
               for argument in \"$@\"; do printf 'arg=<%s>\\n' \"$argument\"; done\n\
               printf 'cwd=<%s>\\n' \"$PWD\"\n\
               printf 'env-begin\\n'\n\
               /usr/bin/env | /usr/bin/sort\n\
               printf 'env-end\\n'\n\
             } > .depscan-tool-capture\n",
        );
        match behavior {
            FakeBehavior::Valid(output) => {
                script.push_str("/bin/cat <<'DEPSCAN_TOOL_OUTPUT'\n");
                script.push_str(output);
                script.push_str("\nDEPSCAN_TOOL_OUTPUT\n");
            }
            FakeBehavior::Malformed => script.push_str("printf '%s\\n' 'not machine data'\n"),
            FakeBehavior::Oversized => {
                script.push_str("while :; do printf '");
                script.push_str(&"0123456789abcdef".repeat(512));
                script.push_str("'; done\n");
            }
            FakeBehavior::Failing => {
                script.push_str("printf '%s\\n' 'fixture restore failed' >&2\nexit 23\n")
            }
            FakeBehavior::Hanging => script.push_str("while :; do :; done\n"),
        }
        fs::write(&executable, script).expect("write fake executable");
        let mut permissions = fs::metadata(&executable).unwrap().permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(executable, permissions).expect("make fake executable runnable");
    }

    fn seed_dump(&self, ecosystem: &str) {
        fs::write(
            self.cache.join(".depscan-cache.json"),
            r#"{"schema_version":1,"owner":"depscan"}"#,
        )
        .expect("write cache sentinel");
        let offline = self.cache.join("offline");
        fs::create_dir(&offline).expect("create offline cache");
        zip::ZipWriter::new(
            fs::File::create(offline.join(format!("{ecosystem}.zip")))
                .expect("create empty OSV dump"),
        )
        .finish()
        .expect("finish empty OSV dump");
        fs::write(
            offline.join(format!("{ecosystem}.synced-at")),
            Utc::now().to_rfc3339(),
        )
        .expect("write dump timestamp");
    }

    fn seed_npm_registry(&self, name: &str, versions: &[&str]) {
        let latest = versions.last().expect("registry fixture has a version");
        let value = serde_json::json!({
            "dist-tags": {"latest": latest},
            "versions": versions
                .iter()
                .map(|version| ((*version).to_owned(), serde_json::json!({})))
                .collect::<serde_json::Map<_, _>>()
        });
        self.seed_registry_value(&format!("npm:{name}"), value);
    }

    fn seed_nuget_registry(&self, name: &str, versions: &[&str]) {
        self.seed_registry_value(
            &format!("nuget:{}", name.to_ascii_lowercase()),
            serde_json::json!({"versions": versions}),
        );
    }

    fn seed_registry_value(&self, key: &str, value: serde_json::Value) {
        let digest = Sha256::digest(key.as_bytes());
        let filename = digest
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        let directory = self.cache.join("registry");
        fs::create_dir_all(&directory).expect("create registry cache");
        fs::write(
            directory.join(format!("{filename}.json")),
            serde_json::to_vec(&serde_json::json!({
                "stored_at": Utc::now().to_rfc3339(),
                "etag": null,
                "value": value,
            }))
            .expect("encode registry cache entry"),
        )
        .expect("write registry cache entry");
    }

    fn run(&self, arguments: &[&str]) -> Output {
        self.run_with_path(arguments, self.test_path())
    }

    fn run_with_path(&self, arguments: &[&str], path: std::ffi::OsString) -> Output {
        Command::new(env!("CARGO_BIN_EXE_depscan"))
            .env_clear()
            .env("PATH", path)
            .env("DEPSCAN_CACHE_DIR", &self.cache)
            .env("NO_COLOR", "1")
            .env("DEPSCAN_SHOULD_NOT_LEAK", "secret fixture value")
            .args(arguments)
            .output()
            .expect("run depscan")
    }

    fn test_path(&self) -> std::ffi::OsString {
        env::join_paths([
            self.bin.clone(),
            PathBuf::from("relative-entry-must-be-removed"),
            PathBuf::from("/usr/bin"),
            PathBuf::from("/bin"),
        ])
        .expect("construct test PATH")
    }

    fn expected_child_path(&self) -> std::ffi::OsString {
        env::join_paths([
            self.bin.clone(),
            PathBuf::from("/usr/bin"),
            PathBuf::from("/bin"),
        ])
        .expect("construct expected sanitized PATH")
    }

    fn capture(&self) -> String {
        fs::read_to_string(self.project.join(".depscan-tool-capture"))
            .expect("read fake executable capture")
    }

    fn capture_exists(&self) -> bool {
        self.project.join(".depscan-tool-capture").exists()
    }
}

fn assert_exit(output: &Output, expected: i32) {
    assert_eq!(
        output.status.code(),
        Some(expected),
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn report_package_names(output: &Output) -> BTreeSet<String> {
    let report: serde_json::Value =
        serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
            panic!(
                "invalid JSON report: {error}\n{}",
                String::from_utf8_lossy(&output.stdout)
            )
        });
    report["results"]
        .as_array()
        .expect("report results")
        .iter()
        .map(|result| result["package"]["name"].as_str().unwrap().to_owned())
        .collect()
}

fn report(output: &Output) -> serde_json::Value {
    serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
        panic!(
            "invalid JSON report: {error}\n{}",
            String::from_utf8_lossy(&output.stdout)
        )
    })
}

fn captured_environment(capture: &str) -> BTreeMap<String, String> {
    let lines = capture.lines().collect::<Vec<_>>();
    let start = lines
        .iter()
        .position(|line| *line == "env-begin")
        .expect("environment start marker");
    let end = lines
        .iter()
        .position(|line| *line == "env-end")
        .expect("environment end marker");
    lines[start + 1..end]
        .iter()
        .map(|line| {
            line.split_once('=')
                .map(|(key, value)| (key.to_owned(), value.to_owned()))
                .unwrap_or_else(|| panic!("malformed captured environment line {line:?}"))
        })
        .collect()
}

fn assert_controlled_invocation(fixture: &Fixture, expected_arguments: &[&str], capture: &str) {
    let mut lines = capture.lines();
    assert_eq!(
        lines.next(),
        Some(format!("argc=<{}>", expected_arguments.len()).as_str())
    );
    for expected in expected_arguments {
        assert_eq!(lines.next(), Some(format!("arg=<{expected}>").as_str()));
    }
    let canonical_project = fs::canonicalize(&fixture.project).unwrap();
    assert_eq!(
        lines.next(),
        Some(format!("cwd=<{}>", canonical_project.display()).as_str())
    );

    let environment = captured_environment(capture);
    assert_eq!(
        environment.get("PATH").map(String::as_str),
        fixture.expected_child_path().to_str()
    );
    for (key, value) in [
        ("CI", "1"),
        ("NO_COLOR", "1"),
        ("LANG", "C"),
        ("LC_ALL", "C"),
        ("TZ", "UTC"),
        ("DOTNET_CLI_TELEMETRY_OPTOUT", "1"),
        ("DOTNET_NOLOGO", "1"),
        ("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", "1"),
    ] {
        assert_eq!(environment.get(key).map(String::as_str), Some(value));
    }
    let home = environment.get("HOME").expect("isolated HOME");
    assert!(
        home.contains("depscan-tool-"),
        "unexpected tool home {home}"
    );
    for key in ["USERPROFILE", "TMPDIR", "TMP", "TEMP", "DOTNET_CLI_HOME"] {
        assert_eq!(environment.get(key), Some(home), "unexpected {key}");
    }
    assert!(!environment.contains_key("DEPSCAN_SHOULD_NOT_LEAK"));
    assert!(!environment["PATH"].contains("relative-entry-must-be-removed"));
    let explicit = BTreeSet::from([
        "CI",
        "DOTNET_CLI_HOME",
        "DOTNET_CLI_TELEMETRY_OPTOUT",
        "DOTNET_NOLOGO",
        "DOTNET_SKIP_FIRST_TIME_EXPERIENCE",
        "HOME",
        "LANG",
        "LC_ALL",
        "NO_COLOR",
        "PATH",
        "TEMP",
        "TMP",
        "TMPDIR",
        "TZ",
        "USERPROFILE",
    ]);
    let shell_internal = BTreeSet::from(["PWD", "SHLVL", "_"]);
    let unexpected = environment
        .keys()
        .map(String::as_str)
        .filter(|key| !explicit.contains(key) && !shell_internal.contains(key))
        .collect::<Vec<_>>();
    assert!(
        unexpected.is_empty(),
        "unexpected inherited environment keys: {unexpected:?}"
    );
}
