#![cfg(unix)]

use chrono::Utc;
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    os::unix::fs::PermissionsExt,
    path::PathBuf,
    process::{Command, Output},
};

const BUN_OUTPUT: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.npmjs.org/left-pad/-/left-pad-1.3.0.tgz"
"#;

const DOTNET_OUTPUT: &str = r#"{
  "version": 1,
  "parameters": "--include-transitive",
  "projects": [{
    "path": "Project.csproj",
    "frameworks": [{
      "framework": "net10.0",
      "topLevelPackages": [{
        "id": "Humanizer.Core",
        "requestedVersion": "2.14.1",
        "resolvedVersion": "2.14.1"
      }],
      "transitivePackages": [{
        "id": "Microsoft.Extensions.Options",
        "resolvedVersion": "10.0.2"
      }]
    }]
  }]
}"#;

const EMPTY_DOTNET_OUTPUT: &str = r#"{
  "version": 1,
  "parameters": "--include-transitive",
  "projects": [{
    "path": "Project.csproj",
    "frameworks": [{"framework": "net10.0"}]
  }]
}"#;

#[derive(Clone, Copy)]
enum FakeBehavior {
    Valid(&'static str),
    Malformed,
    Oversized,
    Failing,
    Hanging,
}

struct Fixture {
    directory: tempfile::TempDir,
    project: PathBuf,
    bin: PathBuf,
    cache: PathBuf,
}

impl Fixture {
    fn new() -> Self {
        let directory = tempfile::tempdir().expect("create test directory");
        let project = directory.path().join("project");
        let bin = directory.path().join("bin");
        let cache = directory.path().join("cache");
        fs::create_dir(&project).expect("create project directory");
        fs::create_dir(&bin).expect("create fake executable directory");
        fs::create_dir(&cache).expect("create cache directory");
        Self {
            directory,
            project,
            bin,
            cache,
        }
    }

    fn bun_project(&self) {
        fs::write(self.project.join("bun.lockb"), b"binary fixture")
            .expect("write binary lock placeholder");
        fs::write(
            self.project.join("package.json"),
            r#"{"dependencies":{"left-pad":"^1.3.0"}}"#,
        )
        .expect("write package manifest");
    }

    fn dotnet_project(&self) {
        fs::write(
            self.project.join("Project.csproj"),
            r#"<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="Humanizer.Core" Version="2.14.1" /></ItemGroup></Project>"#,
        )
        .expect("write .NET project");
    }

    fn install(&self, tool: &str, behavior: FakeBehavior) {
        let executable = self.bin.join(tool);
        let mut script = String::from(
            "#!/bin/sh\n\
             {\n\
               printf 'argc=<%s>\\n' \"$#\"\n\
               for argument in \"$@\"; do printf 'arg=<%s>\\n' \"$argument\"; done\n\
               printf 'cwd=<%s>\\n' \"$PWD\"\n\
               printf 'env-begin\\n'\n\
               /usr/bin/env | /usr/bin/sort\n\
               printf 'env-end\\n'\n\
             } > .depscan-tool-capture\n",
        );
        match behavior {
            FakeBehavior::Valid(output) => {
                script.push_str("/bin/cat <<'DEPSCAN_TOOL_OUTPUT'\n");
                script.push_str(output);
                script.push_str("\nDEPSCAN_TOOL_OUTPUT\n");
            }
            FakeBehavior::Malformed => script.push_str("printf '%s\\n' 'not machine data'\n"),
            FakeBehavior::Oversized => {
                script.push_str("while :; do printf '");
                script.push_str(&"0123456789abcdef".repeat(512));
                script.push_str("'; done\n");
            }
            FakeBehavior::Failing => {
                script.push_str("printf '%s\\n' 'fixture restore failed' >&2\nexit 23\n")
            }
            FakeBehavior::Hanging => script.push_str("while :; do :; done\n"),
        }
        fs::write(&executable, script).expect("write fake executable");
        let mut permissions = fs::metadata(&executable).unwrap().permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(executable, permissions).expect("make fake executable runnable");
    }

    fn seed_dump(&self, ecosystem: &str) {
        fs::write(
            self.cache.join(".depscan-cache.json"),
            r#"{"schema_version":1,"owner":"depscan"}"#,
        )
        .expect("write cache sentinel");
        let offline = self.cache.join("offline");
        fs::create_dir(&offline).expect("create offline cache");
        zip::ZipWriter::new(
            fs::File::create(offline.join(format!("{ecosystem}.zip")))
                .expect("create empty OSV dump"),
        )
        .finish()
        .expect("finish empty OSV dump");
        fs::write(
            offline.join(format!("{ecosystem}.synced-at")),
            Utc::now().to_rfc3339(),
        )
        .expect("write dump timestamp");
    }

    fn run(&self, arguments: &[&str]) -> Output {
        self.run_with_path(arguments, self.test_path())
    }

    fn run_with_path(&self, arguments: &[&str], path: std::ffi::OsString) -> Output {
        Command::new(env!("CARGO_BIN_EXE_depscan"))
            .env_clear()
            .env("PATH", path)
            .env("DEPSCAN_CACHE_DIR", &self.cache)
            .env("NO_COLOR", "1")
            .env("DEPSCAN_SHOULD_NOT_LEAK", "secret fixture value")
            .args(arguments)
            .output()
            .expect("run depscan")
    }

    fn test_path(&self) -> std::ffi::OsString {
        env::join_paths([
            self.bin.clone(),
            PathBuf::from("relative-entry-must-be-removed"),
            PathBuf::from("/usr/bin"),
            PathBuf::from("/bin"),
        ])
        .expect("construct test PATH")
    }

    fn expected_child_path(&self) -> std::ffi::OsString {
        env::join_paths([
            self.bin.clone(),
            PathBuf::from("/usr/bin"),
            PathBuf::from("/bin"),
        ])
        .expect("construct expected sanitized PATH")
    }

    fn capture(&self) -> String {
        fs::read_to_string(self.project.join(".depscan-tool-capture"))
            .expect("read fake executable capture")
    }

    fn capture_exists(&self) -> bool {
        self.project.join(".depscan-tool-capture").exists()
    }
}

fn assert_exit(output: &Output, expected: i32) {
    assert_eq!(
        output.status.code(),
        Some(expected),
        "stdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn report_package_names(output: &Output) -> BTreeSet<String> {
    let report: serde_json::Value =
        serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
            panic!(
                "invalid JSON report: {error}\n{}",
                String::from_utf8_lossy(&output.stdout)
            )
        });
    report["results"]
        .as_array()
        .expect("report results")
        .iter()
        .map(|result| result["package"]["name"].as_str().unwrap().to_owned())
        .collect()
}

fn captured_environment(capture: &str) -> BTreeMap<String, String> {
    let lines = capture.lines().collect::<Vec<_>>();
    let start = lines
        .iter()
        .position(|line| *line == "env-begin")
        .expect("environment start marker");
    let end = lines
        .iter()
        .position(|line| *line == "env-end")
        .expect("environment end marker");
    lines[start + 1..end]
        .iter()
        .map(|line| {
            line.split_once('=')
                .map(|(key, value)| (key.to_owned(), value.to_owned()))
                .unwrap_or_else(|| panic!("malformed captured environment line {line:?}"))
        })
        .collect()
}

fn assert_controlled_invocation(fixture: &Fixture, expected_arguments: &[&str], capture: &str) {
    let mut lines = capture.lines();
    assert_eq!(
        lines.next(),
        Some(format!("argc=<{}>", expected_arguments.len()).as_str())
    );
    for expected in expected_arguments {
        assert_eq!(lines.next(), Some(format!("arg=<{expected}>").as_str()));
    }
    let canonical_project = fs::canonicalize(&fixture.project).unwrap();
    assert_eq!(
        lines.next(),
        Some(format!("cwd=<{}>", canonical_project.display()).as_str())
    );

    let environment = captured_environment(capture);
    assert_eq!(
        environment.get("PATH").map(String::as_str),
        fixture.expected_child_path().to_str()
    );
    for (key, value) in [
        ("CI", "1"),
        ("NO_COLOR", "1"),
        ("LANG", "C"),
        ("LC_ALL", "C"),
        ("TZ", "UTC"),
        ("DOTNET_CLI_TELEMETRY_OPTOUT", "1"),
        ("DOTNET_NOLOGO", "1"),
        ("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", "1"),
    ] {
        assert_eq!(environment.get(key).map(String::as_str), Some(value));
    }
    let home = environment.get("HOME").expect("isolated HOME");
    assert!(
        home.contains("depscan-tool-"),
        "unexpected tool home {home}"
    );
    for key in ["USERPROFILE", "TMPDIR", "TMP", "TEMP", "DOTNET_CLI_HOME"] {
        assert_eq!(environment.get(key), Some(home), "unexpected {key}");
    }
    assert!(!environment.contains_key("DEPSCAN_SHOULD_NOT_LEAK"));
    assert!(!environment["PATH"].contains("relative-entry-must-be-removed"));
    let explicit = BTreeSet::from([
        "CI",
        "DOTNET_CLI_HOME",
        "DOTNET_CLI_TELEMETRY_OPTOUT",
        "DOTNET_NOLOGO",
        "DOTNET_SKIP_FIRST_TIME_EXPERIENCE",
        "HOME",
        "LANG",
        "LC_ALL",
        "NO_COLOR",
        "PATH",
        "TEMP",
        "TMP",
        "TMPDIR",
        "TZ",
        "USERPROFILE",
    ]);
    let shell_internal = BTreeSet::from(["PWD", "SHLVL", "_"]);
    let unexpected = environment
        .keys()
        .map(String::as_str)
        .filter(|key| !explicit.contains(key) && !shell_internal.contains(key))
        .collect::<Vec<_>>();
    assert!(
        unexpected.is_empty(),
        "unexpected inherited environment keys: {unexpected:?}"
    );
}

#[test]
fn explicitly_selected_config_runs_bun_with_exact_sandboxed_invocation() {
    let fixture = Fixture::new();
    fixture.bun_project();
    fixture.install("bun", FakeBehavior::Valid(BUN_OUTPUT));
    fixture.seed_dump("npm");
    let config = fixture.directory.path().join("trusted.toml");
    fs::write(&config, "allow-tools = true\n").unwrap();

    let output = fixture.run(&[
        "scan",
        "--offline",
        "--format",
        "json",
        "--config",
        config.to_str().unwrap(),
        fixture.project.to_str().unwrap(),
    ]);

    assert_exit(&output, 0);
    assert_eq!(
        report_package_names(&output),
        BTreeSet::from(["left-pad".to_owned()])
    );
    let capture = fixture.capture();
    assert_controlled_invocation(&fixture, &["bun.lockb"], &capture);
}

#[test]
fn allow_tools_runs_dotnet_with_exact_project_and_offline_arguments() {
    let fixture = Fixture::new();
    fixture.dotnet_project();
    fixture.install("dotnet", FakeBehavior::Valid(DOTNET_OUTPUT));
    fixture.seed_dump("NuGet");

    let output = fixture.run(&[
        "scan",
        "--offline",
        "--format",
        "json",
        "--allow-tools",
        fixture.project.to_str().unwrap(),
    ]);

    assert_exit(&output, 0);
    assert_eq!(
        report_package_names(&output),
        BTreeSet::from([
            "humanizer.core".to_owned(),
            "microsoft.extensions.options".to_owned(),
        ])
    );
    let capture = fixture.capture();
    assert_controlled_invocation(
        &fixture,
        &[
            "list",
            "./Project.csproj",
            "package",
            "--include-transitive",
            "--format",
            "json",
            "--output-version",
            "1",
            "--verbosity",
            "quiet",
            "--no-restore",
        ],
        &capture,
    );
}

#[test]
fn online_dotnet_profile_does_not_disable_the_authorized_restore() {
    let fixture = Fixture::new();
    fixture.dotnet_project();
    fixture.install("dotnet", FakeBehavior::Valid(EMPTY_DOTNET_OUTPUT));

    let output = fixture.run(&["scan", "--allow-tools", fixture.project.to_str().unwrap()]);

    assert_exit(&output, 20);
    let capture = fixture.capture();
    assert_controlled_invocation(
        &fixture,
        &[
            "list",
            "./Project.csproj",
            "package",
            "--include-transitive",
            "--format",
            "json",
            "--output-version",
            "1",
            "--verbosity",
            "quiet",
        ],
        &capture,
    );
}

#[test]
fn malformed_outputs_are_actionable_for_both_tools() {
    for tool in ["bun", "dotnet"] {
        let fixture = Fixture::new();
        if tool == "bun" {
            fixture.bun_project();
        } else {
            fixture.dotnet_project();
        }
        fixture.install(tool, FakeBehavior::Malformed);
        let output = fixture.run(&["scan", "--allow-tools", fixture.project.to_str().unwrap()]);

        assert_exit(&output, 10);
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("emitted malformed dependency data"),
            "{tool}: {stderr}"
        );
        assert!(fixture.capture_exists());
    }
}

#[test]
fn oversized_output_is_rejected_and_the_tool_is_stopped() {
    let fixture = Fixture::new();
    fixture.bun_project();
    fixture.install("bun", FakeBehavior::Oversized);

    let output = fixture.run(&["scan", "--allow-tools", fixture.project.to_str().unwrap()]);

    assert_exit(&output, 10);
    assert!(String::from_utf8_lossy(&output.stderr).contains("8388608-byte output limit"));
    assert!(fixture.capture_exists());
}

#[test]
fn nonzero_tool_exit_includes_bounded_actionable_stderr() {
    let fixture = Fixture::new();
    fixture.dotnet_project();
    fixture.install("dotnet", FakeBehavior::Failing);

    let output = fixture.run(&["scan", "--allow-tools", fixture.project.to_str().unwrap()]);

    assert_exit(&output, 10);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("exited with exit status: 23"), "{stderr}");
    assert!(stderr.contains("fixture restore failed"), "{stderr}");
    assert!(stderr.contains("commit packages.lock.json"), "{stderr}");
}

#[test]
fn hanging_tool_is_killed_at_the_timeout() {
    let fixture = Fixture::new();
    fixture.bun_project();
    fixture.install("bun", FakeBehavior::Hanging);

    let started = std::time::Instant::now();
    let output = fixture.run(&["scan", "--allow-tools", fixture.project.to_str().unwrap()]);

    assert_exit(&output, 10);
    assert!(String::from_utf8_lossy(&output.stderr).contains("timed out after 10 seconds"));
    assert!(started.elapsed() < std::time::Duration::from_secs(13));
}

#[test]
fn missing_tool_is_an_actionable_parse_failure() {
    let fixture = Fixture::new();
    fixture.bun_project();
    let empty_path = env::join_paths([fixture.bin.clone()]).unwrap();

    let output = fixture.run_with_path(
        &["scan", "--allow-tools", fixture.project.to_str().unwrap()],
        empty_path,
    );

    assert_exit(&output, 10);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("executable was not found"), "{stderr}");
    assert!(stderr.contains("commit the generated bun.lock"), "{stderr}");
}

#[test]
fn tools_are_never_started_without_effective_authorization() {
    let bun = Fixture::new();
    bun.bun_project();
    bun.install("bun", FakeBehavior::Valid(BUN_OUTPUT));
    let output = bun.run(&["scan", bun.project.to_str().unwrap()]);
    assert_exit(&output, 10);
    assert!(!bun.capture_exists());

    let dotnet = Fixture::new();
    dotnet.dotnet_project();
    dotnet.install("dotnet", FakeBehavior::Valid(DOTNET_OUTPUT));
    dotnet.seed_dump("NuGet");
    let output = dotnet.run(&[
        "scan",
        "--offline",
        "--format",
        "json",
        dotnet.project.to_str().unwrap(),
    ]);
    assert_exit(&output, 0);
    assert_eq!(
        report_package_names(&output),
        BTreeSet::from(["humanizer.core".to_owned()])
    );
    assert!(!dotnet.capture_exists());

    let implicit = Fixture::new();
    implicit.bun_project();
    implicit.install("bun", FakeBehavior::Valid(BUN_OUTPUT));
    fs::write(
        implicit.project.join("depscan.toml"),
        "allow-tools = true\n",
    )
    .unwrap();
    let output = implicit.run(&["scan", implicit.project.to_str().unwrap()]);
    assert_exit(&output, 10);
    assert!(
        String::from_utf8_lossy(&output.stderr)
            .contains("implicit project config cannot enable allow-tools")
    );
    assert!(!implicit.capture_exists());
}
