use depscan_core::{DetectedSource, EcosystemParser, Package, SourceKind};
use depscan_parsers::PythonParser;
use serde_json::{Value, json};
use std::{fs, path::PathBuf};

fn fixture(case: &str, file: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/python")
        .join(case)
        .join(file)
}

fn parse(case: &str, file: &str, kind: SourceKind) -> Vec<Package> {
    PythonParser
        .parse(&DetectedSource {
            path: fixture(case, file),
            kind,
        })
        .unwrap()
}

fn snapshot(packages: &[Package]) -> Value {
    Value::Array(
        packages
            .iter()
            .map(|package| {
                json!({
                    "name": package.name,
                    "version": package.version,
                    "direct": package.direct,
                    "direct_known": package.direct_known,
                    "dev": package.dev,
                    "dev_known": package.dev_known,
                    "enrichable": package.enrichable,
                    "source": package.source_file.file_name().and_then(|name| name.to_str()),
                })
            })
            .collect(),
    )
}

#[test]
fn parses_current_uv_sources_directness_groups_and_transitive_scope() {
    let packages = parse("uv-current", "uv.lock", SourceKind::UvLock);

    assert!(packages.iter().all(|package| package.direct_known));
    assert!(packages.iter().all(|package| package.dev_known));
    assert!(
        packages.iter().all(|package| package.name != "uv-fixture"),
        "the project root is not a dependency"
    );
    insta::assert_json_snapshot!("uv_current_provenance", snapshot(&packages));
}

#[test]
fn parses_current_poetry_sources_manifest_directness_and_groups() {
    let packages = parse("poetry-current", "poetry.lock", SourceKind::PoetryLock);

    assert!(packages.iter().all(|package| package.direct_known));
    assert!(packages.iter().all(|package| package.dev_known));
    insta::assert_json_snapshot!("poetry_current_provenance", snapshot(&packages));
}

#[test]
fn poetry_without_a_manifest_keeps_directness_unknown() {
    let directory = tempfile::tempdir().unwrap();
    let lock = directory.path().join("poetry.lock");
    fs::copy(fixture("poetry-current", "poetry.lock"), &lock).unwrap();

    let packages = PythonParser
        .parse(&DetectedSource {
            path: lock.clone(),
            kind: SourceKind::PoetryLock,
        })
        .unwrap();

    assert!(packages.iter().all(|package| !package.direct));
    assert!(packages.iter().all(|package| !package.direct_known));
    assert!(packages.iter().all(|package| package.dev_known));
}

#[test]
fn parses_legacy_poetry_category_and_group_less_metadata() {
    let directory = tempfile::tempdir().unwrap();
    let lock = directory.path().join("poetry.lock");
    fs::write(
        &lock,
        r#"[[package]]
name = "runtime"
version = "1.0.0"
category = "main"
optional = false

[[package]]
name = "test-only"
version = "2.0.0"
category = "dev"
optional = false

[metadata]
lock-version = "1.1"
"#,
    )
    .unwrap();

    let packages = PythonParser
        .parse(&DetectedSource {
            path: lock.clone(),
            kind: SourceKind::PoetryLock,
        })
        .unwrap();
    assert!(!packages[0].dev);
    assert!(packages[1].dev);
    assert!(packages.iter().all(|package| !package.direct_known));

    fs::write(
        &lock,
        r#"# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.

[[package]]
name = "runtime"
version = "1.0.0"
optional = false

[[package]]
name = "test-only"
version = "2.0.0"
optional = false

[metadata]
lock-version = "2.0"
"#,
    )
    .unwrap();

    let packages = PythonParser
        .parse(&DetectedSource {
            path: lock,
            kind: SourceKind::PoetryLock,
        })
        .unwrap();
    assert!(packages.iter().all(|package| !package.dev));
    assert!(packages.iter().all(|package| !package.dev_known));
    assert!(packages.iter().all(|package| !package.direct_known));
}

#[test]
fn follows_uv_manifest_extras_from_script_locks() {
    let directory = tempfile::tempdir().unwrap();
    let lock = directory.path().join("script.py.lock");
    fs::write(
        &lock,
        r#"version = 1
revision = 3
requires-python = ">=3.12"

[manifest]
requirements = [{ name = "provider", extras = ["feature"], specifier = "==1.0.0" }]

[[package]]
name = "extra-transitive"
version = "2.0.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "provider"
version = "1.0.0"
source = { registry = "https://pypi.org/simple" }

[package.optional-dependencies]
feature = [{ name = "extra-transitive" }]
"#,
    )
    .unwrap();

    let packages = PythonParser
        .parse(&DetectedSource {
            path: lock,
            kind: SourceKind::UvLock,
        })
        .unwrap();

    let provider = packages
        .iter()
        .find(|package| package.name == "provider")
        .unwrap();
    assert!(provider.direct);
    assert!(provider.direct_known);
    assert!(!provider.dev);
    assert!(provider.dev_known);

    let extra = packages
        .iter()
        .find(|package| package.name == "extra-transitive")
        .unwrap();
    assert!(!extra.direct);
    assert!(extra.direct_known);
    assert!(!extra.dev);
    assert!(extra.dev_known);
}

#[test]
fn rejects_unsupported_and_malformed_uv_lockfiles_with_context() {
    let valid = r#"version = 1
revision = 3
requires-python = ">=3.12"

[[package]]
name = "dependency"
version = "1.0.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "root"
version = "0.1.0"
source = { virtual = "." }
dependencies = [{ name = "dependency" }]
"#;
    for (case, input, expected) in [
        (
            "future-version",
            valid.replacen("version = 1", "version = 2", 1),
            "unsupported uv lockfile version 2",
        ),
        (
            "negative-revision",
            valid.replace("revision = 3", "revision = -1"),
            "revision must be a non-negative integer",
        ),
        (
            "mixed-source",
            valid.replace(
                "source = { registry = \"https://pypi.org/simple\" }",
                "source = { registry = \"https://pypi.org/simple\", path = \"dep.whl\" }",
            ),
            "exactly one supported source kind",
        ),
        (
            "missing-dependency",
            valid.replace(
                "name = \"dependency\"\nversion",
                "name = \"other\"\nversion",
            ),
            "has no matching package entry",
        ),
        (
            "ambiguous-dependency",
            valid.replace(
                "[[package]]\nname = \"root\"",
                "[[package]]\nname = \"dependency\"\nversion = \"2.0.0\"\nsource = { registry = \"https://pypi.org/simple\" }\n\n[[package]]\nname = \"root\"",
            ),
            "is ambiguous; version and source are required",
        ),
        (
            "invalid-version",
            valid.replacen("version = \"1.0.0\"", "version = \"not a version\"", 1),
            "not valid PEP 440",
        ),
        (
            "unknown-source-field",
            valid.replace(
                "source = { registry = \"https://pypi.org/simple\" }",
                "source = { registry = \"https://pypi.org/simple\", mystery = true }",
            ),
            "unsupported field \"mystery\"",
        ),
        (
            "malformed-package",
            valid.replace("name = \"dependency\"", "name = false"),
            "missing a non-empty string name",
        ),
        (
            "invalid-package-name",
            valid.replace("name = \"dependency\"", "name = \".dependency\""),
            "contains invalid Python package name",
        ),
    ] {
        let directory = tempfile::tempdir().unwrap();
        let lock = directory.path().join("uv.lock");
        fs::write(&lock, input).unwrap();
        let error = PythonParser
            .parse(&DetectedSource {
                path: lock,
                kind: SourceKind::UvLock,
            })
            .unwrap_err()
            .to_string();
        assert!(error.contains(expected), "{case}: {error}");
        assert!(error.contains("uv.lock"), "{case}: {error}");
    }
}

#[test]
fn rejects_unsupported_and_malformed_poetry_lockfiles_with_context() {
    let valid = r#"[[package]]
name = "dependency"
version = "1.0.0"
optional = false
groups = ["main"]

[metadata]
lock-version = "2.1"
"#;
    for (case, input, expected) in [
        (
            "future-version",
            valid.replace("lock-version = \"2.1\"", "lock-version = \"2.2\""),
            "unsupported Poetry lock-version \"2.2\"",
        ),
        (
            "missing-optional",
            valid.replace("optional = false\n", ""),
            "missing a boolean optional",
        ),
        (
            "malformed-groups",
            valid.replace("groups = [\"main\"]", "groups = \"main\""),
            "missing an array groups",
        ),
        (
            "invalid-version",
            valid.replace("version = \"1.0.0\"", "version = \"bad version\""),
            "not valid PEP 440",
        ),
        (
            "invalid-package-name",
            valid.replace("name = \"dependency\"", "name = \"dependency-\""),
            "contains invalid Python package name",
        ),
        (
            "missing-metadata",
            valid.replace("[metadata]\nlock-version = \"2.1\"\n", ""),
            "missing a metadata table",
        ),
        (
            "unsupported-source",
            valid.replace(
                "groups = [\"main\"]",
                "groups = [\"main\"]\n\n[package.source]\ntype = \"mystery\"\nurl = \"https://example.invalid\"",
            ),
            "unsupported Poetry source type \"mystery\"",
        ),
    ] {
        let directory = tempfile::tempdir().unwrap();
        let lock = directory.path().join("poetry.lock");
        fs::write(&lock, input).unwrap();
        let error = PythonParser
            .parse(&DetectedSource {
                path: lock,
                kind: SourceKind::PoetryLock,
            })
            .unwrap_err()
            .to_string();
        assert!(error.contains(expected), "{case}: {error}");
        assert!(error.contains("poetry.lock"), "{case}: {error}");
    }
}
