use depscan_parsers::{parse_bun_lockb_output, parse_dotnet_list_json};
use std::fs;

#[test]
fn parses_bun_binary_lock_yarn_output_with_manifest_directness() {
    let directory = tempfile::tempdir().unwrap();
    let lock = directory.path().join("bun.lockb");
    fs::write(
        directory.path().join("package.json"),
        r#"{"dependencies":{"left-pad":"^1.3.0"},"devDependencies":{"ansi-regex":"^6"}}"#,
    )
    .unwrap();
    let output = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.npmjs.org/left-pad/-/left-pad-1.3.0.tgz"

ansi-regex@^6.0.0:
  version "6.2.2"
  resolved "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.2.2.tgz"

balanced-match@^1.0.0:
  version "1.0.2"
  resolved "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz"
"#;

    let packages = parse_bun_lockb_output(&lock, output).unwrap();
    assert_eq!(packages.len(), 3);
    let left_pad = packages
        .iter()
        .find(|package| package.name == "left-pad")
        .unwrap();
    assert_eq!(left_pad.version, "1.3.0");
    assert!(left_pad.direct);
    assert!(!left_pad.dev);
    assert_eq!(left_pad.source_file, lock);
    let ansi_regex = packages
        .iter()
        .find(|package| package.name == "ansi-regex")
        .unwrap();
    assert!(ansi_regex.direct);
    assert!(ansi_regex.dev);
    assert!(
        packages
            .iter()
            .find(|package| package.name == "balanced-match")
            .is_some_and(|package| !package.direct)
    );
}

#[test]
fn rejects_non_yarn_bun_binary_lock_output() {
    let error = parse_bun_lockb_output(
        std::path::Path::new("bun.lockb"),
        r#"{"lockfileVersion":2}"#,
    )
    .unwrap_err()
    .to_string();
    assert!(error.contains("did not emit a Yarn Classic lockfile"));
}

#[test]
fn parses_dotnet_json_output_and_merges_framework_directness() {
    let path = std::path::Path::new("Project.csproj");
    let output = r#"{
      "version": 1,
      "parameters": "--include-transitive",
      "projects": [{
        "path": "/checkout/Project.csproj",
        "frameworks": [{
          "framework": "net8.0",
          "topLevelPackages": [{
            "id": "Humanizer.Core",
            "requestedVersion": "2.14.1",
            "resolvedVersion": "2.14.1"
          }],
          "transitivePackages": [{
            "id": "Microsoft.Extensions.Options",
            "resolvedVersion": "8.0.2"
          }]
        }, {
          "framework": "net10.0",
          "topLevelPackages": [{
            "id": "Microsoft.Extensions.Options",
            "requestedVersion": "8.0.0",
            "resolvedVersion": "8.0.2"
          }]
        }]
      }]
    }"#;

    let packages = parse_dotnet_list_json(path, output).unwrap();
    assert_eq!(packages.len(), 2);
    assert!(packages.iter().all(|package| package.source_file == path));
    assert!(
        packages
            .iter()
            .find(|package| package.name == "humanizer.core")
            .is_some_and(|package| package.direct && package.version == "2.14.1")
    );
    assert!(
        packages
            .iter()
            .find(|package| package.name == "microsoft.extensions.options")
            .is_some_and(|package| package.direct && package.version == "8.0.2")
    );
}

#[test]
fn rejects_malformed_dotnet_json_contracts() {
    let path = std::path::Path::new("Project.csproj");
    for (case, output, expected) in [
        ("syntax", "not json", "expected ident"),
        (
            "version",
            r#"{"version":2,"projects":[]}"#,
            "unsupported dotnet package-list output version 2",
        ),
        (
            "project-count",
            r#"{"version":1,"projects":[]}"#,
            "exactly one requested project",
        ),
        (
            "wrong-project",
            r#"{"version":1,"projects":[{"path":"Other.csproj","frameworks":[]}]}"#,
            "not the requested project",
        ),
        (
            "no-framework",
            r#"{"version":1,"projects":[{"path":"Project.csproj","frameworks":[]}]}"#,
            "did not report any target frameworks",
        ),
        (
            "invalid-version",
            r#"{"version":1,"projects":[{"path":"Project.csproj","frameworks":[{"framework":"net10.0","topLevelPackages":[{"id":"Example","resolvedVersion":"latest"}]}]}]}"#,
            "invalid NuGet version",
        ),
        (
            "problems",
            r#"{"version":1,"problems":[{"level":"error"}],"projects":[{"path":"Project.csproj","frameworks":[{"framework":"net10.0"}]}]}"#,
            "reported 1 problem",
        ),
    ] {
        let error = parse_dotnet_list_json(path, output)
            .unwrap_err()
            .to_string();
        assert!(error.contains(expected), "{case}: {error}");
    }
}
