[package]
name = "depscan-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
description = "Core data model and version and advisory matching for depscan"
include = ["src/**", "LICENSE"]

[dependencies]
async-trait.workspace = true
chrono.workspace = true
js-semver.workspace = true
pep440_rs.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
